[package]
name = "neorusty-server-core"
version = "0.1.0"
edition = "2024"

[dependencies]
neorusty-core = { path = "../core" }
getrandom = "0.2"
pumpkin = { path = "../../pumpkin-master/pumpkin" }
pumpkin-config = { path = "../../pumpkin-master/pumpkin-config" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "signal", "sync"] }
