[package]
name = "neorusty"
version = "0.1.0"
edition = "2024"

[dependencies]
neorusty-core = { path = "../core" }
neorusty-plugin-system = { path = "../plugin-system" }
neorusty-api = { path = "../api" }
neorusty-server-core = { path = "../server-core" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "signal"] }

[dev-dependencies]
neorusty-macros = { path = "../neorusty-macros" }
