name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'dev-*'
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: neoforged/actions/checkout@main

      - name: Setup JDK 25
        uses: neoforged/actions/setup-java@main
        with:
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Setup with Gradle
        run: ./gradlew setup

      - name: Build with Gradle
        run: ./gradlew assemble checkFormatting

      - name: Run tests
        run: ./gradlew :tests:runUnitTests
