name: Publish PRs to GitHub Packages

on:
  workflow_run:
    workflows: [Build PRs]
    types:
      - completed
  issue_comment:
    types:
      - edited
  pull_request_target:
    types:
      - opened

permissions:
  packages: write

jobs:
  publish-prs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./patched-neoforge
    steps:
      - name: Checkout repository
        uses: neoforged/actions/checkout@main

      - name: Setup JDK
        uses: neoforged/actions/setup-java@main
        with:
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Restore NeoForge source files
        run: bash setup-sources.sh

      - name: Setup with Gradle
        run: ./gradlew setup

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          PR_PUBLISHING_GH_APP_ID: ${{ secrets.PR_PUBLISHING_GH_APP_ID }}
          PR_PUBLISHING_GH_APP_KEY: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}
