name: Publish PR JCC output

on:
  workflow_run:
    workflows: [Build PRs]
    types:
      - completed

permissions:
  contents: read

jobs:
  publish-jcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./neoforge-source
    if: ${{ ! startsWith(github.event.workflow_run.head_branch, 'port/') }}
    steps:
      - name: Checkout repository
        uses: neoforged/actions/checkout@main

      - name: Setup JDK 25
        uses: neoforged/actions/setup-java@main
        with:
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Check JCC
        run: ./gradlew checkJarCompatibility
        env:
          JCC_GH_APP_ID: ${{ secrets.JCC_GH_APP_ID }}
          JCC_GH_APP_KEY: ${{ secrets.JCC_GH_APP_KEY }}
